import React from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer';
import { AppContext } from '../AppContext'
import { Button, TextField, FormControlLabel, Checkbox, Link, Grid, CssBaseline, Container, Typography, Card, Box, CardMedia } from '@mui/material';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { MyContainer, MyTitle } from '../styles.js'
import { Navigate } from 'react-router-dom';
import { ToastContainer, toast } from 'react-toastify';
import theme from '../theme'
import 'react-toastify/dist/ReactToastify.css';

/**
 * Login component to allow users to login to the application.
 * Uses Navigate from React Router Dom to redirect user to home page if user is logged in while trying to
 * enter login page by url
 * 
 * @returns {JSX.Element} Returns the login page JSX element.
 */
export default function Login() {
    // Retrieve the user object and login function from the AppContext
    const { userObj, login, baseURL } = React.useContext(AppContext)
    // React state to store user's input in object format, contains 2 properties: 
    // username and password
    const [formData, setFormData] = React.useState({
        username: "",
        password: "",
    })
    // React state to store login status, contains 2 properties: 
    // status (Boolean) and error message(String)
    const [status, setStatus] = React.useState({
      sucess: false,
      message: ""
    })

    /* this gets the height of the header and footer an subtracts it from the total height of the 
    viewport so the footer is positioned at the bottom of the page */
    const mainRef = React.useRef(null);
    const headerRef = React.useRef(null);
    

    /**
     * This useEffect hook listens to the window resize event and updates the minHeight style
     * property of the mainRef element, which subtracts the height of the header and footer from
     * the total viewport height so the footer is positioned at the bottom of the page.
     * 
     * @function
     * @name handleResize
     * @returns {undefined}
     * 
     * @returns {function} A cleanup function that removes the event listener for window resize.
     */
    React.useEffect(() => {
        const handleResize = () => {
        mainRef.current.style.minHeight = `calc(100vh - ${headerRef.current.clientHeight + document.querySelector('footer').clientHeight}px)`;
        };
        handleResize();
        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
    }, []);


    /**
     * Store user's input to the formDate state
     *
     * @param {object} event - The event object containing the target input's name and value.
     */
    const handleChange = (event) => {
        const { name, value } = event.target
        setFormData(prevFormData => {
            return {
                ...prevFormData,
                [name] : value
            }
        })
        // clear the error message displayed if there are any
        setStatus({
          success: false,
          message: ""
        })
    }

    /**
     * Handles the submission of the login form, sends a POST request to the server,
     * and logs in the user if successful.
     *
     * @param {Object} event - The event object generated by the form submission
     */
    const handleSubmit = async (event) => {
        event.preventDefault()
        try {
            const res = await fetch(`${baseURL}/food_finder/users/login`, 
            {
                headers: {
                  "Content-Type": "application/json"
                },
                method: "POST",
                body: JSON.stringify({
                    username: formData.username,
                    password: formData.password
                })
            })
            if (res.status === 200) {
                const { userObj, token } = await res.json()
                toast.success("Login successfully!")
                login(userObj, token)
            } else if(res.status === 403 || res.status === 404) {
              /* To avoid malicious behaviour, system should not let specify wrong username or wrong password */
              setStatus({
                success: false,
                message: "Invalid username/password"
              })
            } else {
                const data = await res.json()
                const message = data.message
                setStatus({
                  success: false,
                  message: message
                })
            }
        } catch(error) {
            setStatus({
              success: false,
              message: "Error communicating with server"
            })
        }
    }
  return (
    <div>
      {userObj && <Navigate replace to="/"/>}
        <CssBaseline />
      <div ref={headerRef}>
      <Header  />
      </div>
      <Box>

      <main ref={mainRef}>
        <MyContainer maxWidth='sm' >
          <Card> 
            <MyTitle align='center' sx={{ top: '15vh' }}>
              Login
            </MyTitle>
            <Box sx={{ position: 'relative' }}>
              <CardMedia 
                component="img"
                sx={{ height: '30vh', filter: 'brightness(35%)' }}
                image="https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                alt="random"
              /> 
            </Box>
          </Card>
        </MyContainer>
        <Container>
          <ThemeProvider theme={theme}>
            <Container component="main" maxWidth="xs">
              <CssBaseline />
              <Box
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                }}
              >
                <Box component="form" onSubmit={handleSubmit} noValidate sx={{ mt: 1 }}>
                  <TextField
                    margin="normal"
                    required
                    fullWidth
                    id="username"
                    label="Username"
                    name="username"
                    value={formData.username}
                    autoComplete="username"
                    onChange={handleChange}
                    autoFocus
                  />
                  <TextField
                    margin="normal"
                    required
                    fullWidth
                    name="password"
                    value={formData.password}
                    label="Password"
                    type="password"
                    id="password"
                    onChange={handleChange}
                    autoComplete="current-password"
                  />
                  <Box sx={{color: 'red'}}>{status.message}</Box>
                  <Button
                    type="submit"
                    fullWidth
                    variant="contained"
                    sx={{ mt: 3, mb: 2 }}
                    onSubmit={handleSubmit}
                  >
                    Sign In
                  </Button>
                  <Grid container>
                    <Grid item xs>
                      <Link href="/resetpassword" variant="body2">
                        Forgot password?
                      </Link>
                    </Grid>
                    <Grid item>
                      <Link href="/signup" variant="body2">
                        {"Don't have an account? Sign Up"}
                      </Link>
                    </Grid>
                  </Grid>
                </Box>
              </Box>
            </Container>
          </ThemeProvider>
        </Container>
        <ToastContainer
          autoClose={false}
        />
        </main>
      </Box>
        <Footer />
    </div>
  )
}
